on: 
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Release Name"
        required: true
        type: string
      version:
        description: "Release Version"
        required: true
        type: string

name: Build and Sign Release V2

jobs:

  build-and-deploy:
    runs-on: windows-latest
    env:
      CODESIGN_PW: ${{ secrets.TESTSIGN_PWD }}
      CODESIGN_BASE64: ${{ secrets.TESTSIGN_BASE64 }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: repo
    - name: Sign Scripts
      run: |
        $ErrorActionPreference = "Stop"
        $PSDefaultParameterValues['*:ErrorAction']='Stop'
        Set-StrictMode -Version Latest

        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\cert.txt -Value $env:CODESIGN_PFX
        certutil -decode certificate\cert.txt certificate\cert.pfx

        Get-ChildItem -Recurse -Path repo -Include **.ps1,**.psm1 | ForEach-Object {
          $path = $_.FullName
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x86/signtool.exe' sign /t http://timestamp.digicert.com /fd SHA256 /p $env:CODESIGN_PW /f certificate.pfx /td SHA256 $path
        }

        Remove-Item -Recurse -Force certificate
        Remove-Item -Recurse -Force repo -Include .git*

        Compress-Archive -Path repo -DestinationPath release.zip
    - name: release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        name: ${{ inputs.releaseName }}
        tag_name: ${{ inputs.version }}
        files: release.zip
        generate_release_notes: true
        fail_on_unmatched_files: true
